substitutions:
  # Change this to true in case you have a hidden SSID at home.
  hidden_ssid: "false"

globals:
  # Global variable storing the state of initialization. Once connected to HA API, this turns to false.
  - id: init_in_progress
    type: bool
    restore_value: no
    initial_value: 'true'

esphome:
  name: ${name}
  friendly_name: Display
  name_add_mac_suffix: true
  min_version: 2026.2.0
  on_boot:
    - priority: 375
      then:
        - script.execute: control_leds
        - delay: 1s
        # If after 10 minutes, the device is still initializing (It did not yet connect to Home Assistant), turn off the init_in_progress variable and run the script to refresh the UI
        - delay: 10min
        - if:
            condition:
              lambda: return id(init_in_progress);
            then:
              - lambda: id(init_in_progress) = false;
              - script.execute: control_leds


esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

wifi:
  id: wifi_id
  fast_connect: ${hidden_ssid}
  on_connect:
    - script.execute: control_leds
  on_disconnect:
    - script.execute: control_leds

network:
  enable_ipv6: true

# Enable logging
logger:
  level: DEBUG
  logs:
    sensor: WARN  # avoids logging debug sensor updates

# Enable Home Assistant API
api:
  id: api_id
  on_client_connected:
    - lambda: id(init_in_progress) = false;
    - script.execute: control_leds
  on_client_disconnected:
    - script.execute: control_leds
  encryption:   # Uses key set by Home Assistant

ota:
  - platform: esphome
    id: ota_esphome

i2c:
  - id: internal_i2c
    sda: $i2c_sda
    scl: $i2c_scl
    frequency: 400kHz

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

# Time Source (Home Assistant)
time:
  - platform: homeassistant
    id: rtc_time
    on_time:
      # Every minute
      - seconds: 0
        minutes: '*'
        then:
          - script.execute: time_tick

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 5min
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percentage"
    id: wifi_signal_percentage
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true
  kalman_process_error: 0.01

media_source:
  - platform: sendspin
    id: sendspin_source
  - platform: http_request
    id: http_source
    buffer_size: 500000

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: config
    disabled_by_default: true
    icon: "mdi:restart"

debug:
  update_interval: 5s