packages:
  board: !include firmware/board-lcd.yaml
  common:
    file: firmware/common.yaml
    vars:
      name: voice-assistant-display
  display: !include firmware/display.yaml

esphome:
  project:
    name: "stuart-c.esphome-display"
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://stuart-c.github.io/esphome-display/dev/voice
